name: Release go

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64]
        goos: [linux, windows, darwin]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
      - name: Build
        run: |
          mkdir -p dist/
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.goos }}/
      - name: Compress Release
        uses: morning-start/compress-action@v0.0.4
        with:
          file_type: 'zip'
          paths: "dist/${{ matrix.goos }}/*" 
          file_name: 'git-tags-${{ matrix.goos }}-${{ matrix.goarch }}.zip'
          output_dir: "export"
      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          artifacts: "export/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
