name: Release go

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64]
        goos: [linux, windows, darwin]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/git-tags-${{ matrix.goos }}-$GITHUB_REF_NAME.zip
      - name: Package
        run: |
          cd dist
          zip git-tags-${{ matrix.goos }}-$GITHUB_REF_NAME.zip *
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-tags-${{ matrix.goos }}-$GITHUB_REF_NAME
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          artifacts: "dist/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
