name: Release go

on:
  push:
    tags:
      - 'v*'
      
permissions:  # 添加权限设置
    contents: write  # 允许读写仓库内容    
    
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64]
        goos: [linux, windows, darwin]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
      - name: Build
        run: |
          mkdir -p dist/
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.goos }}/
      - name: Compress Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          directory: "dist/${{ matrix.goos }}"
          filename: 'git-tags-${{ matrix.goos }}-${{ github.ref_name }}.zip'
      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          artifacts: "./dist/${{ matrix.goos }}/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
